name: Prison
author: d1lta_
version: '${version}'
main: me.d1lta.prison.Main
api-version: '1.20'
libraries:
  - 'org.apache.commons:commons-pool2:2.9.0'
  - 'redis.clients:jedis:4.3.1'
commands:
  config:
  wcreate:
  wtp:
  giveitem:
    aliases: ["items"]
  sell:
  autosell:
  upgrade:
  admjedis:
  lvl:
    aliases: ["level"]
  spawn:
  mine:
  debug:
  blockstats:
  upgrades:
  summonmob:
  faction:
  base:
  gift:
  warzone:
  enchantments:
  skills: